import { createSlice } from '@reduxjs/toolkit';

const tripSlice = createSlice({
	name: 'calendar',
	initialState: {
        user1: {
			'00-2023': [[false, true], [true, true], [true, true], [false, true], [false, true], [true, false], [true, true], [true, true], [false, true], [false, false], [false, false], [false, false], [false, false], [false, false], [false, true], [false, false], [false, false], [true, false], [true, true], [false, true], [true, true], [true, false], [true, true], [false, false], [true, true], [false, true], [true, false], [false, false], [true, false], [false, false], [true, false]],
            '01-2023': [[true, true], [true, false], [true, false], [true, false], [false, true], [false, true], [false, false], [true, true], [false, true], [true, true], [true, true], [false, false], [false, false], [true, true], [true, true], [true, false], [false, true], [true, true], [false, true], [false, false], [true, true], [false, true], [false, true], [true, true], [true, true], [false, false], [true, false], [true, false]],
            '02-2023': [[true, false], [false, true], [false, false], [false, true], [false, true], [true, true], [true, true], [true, false], [false, false], [true, true], [true, false], [true, false], [false, false], [true, true], [true, true], [false, false], [false, true], [true, true], [true, false], [true, true], [true, true], [true, false], [true, true], [false, true], [true, false], [true, false], [false, true], [false, true], [true, true], [true, true], [false, true]],
            '03-2023': [[false, false], [true, false], [true, true], [false, true], [false, true], [false, true], [true, false], [true, false], [false, true], [false, false], [false, true], [true, true], [true, false], [false, false], [true, true], [true, true], [true, false], [true, true], [false, false], [false, true], [true, true], [false, true], [true, true], [false, true], [false, true], [true, true], [false, true], [false, false], [false, false], [true, false]],
            '04-2023': [[false, true], [true, false], [false, false], [true, true], [false, false], [false, false], [false, true], [false, true], [true, true], [true, true], [false, true], [false, false], [true, false], [true, true], [true, true], [false, false], [false, false], [false, true], [true, true], [false, true], [true, false], [false, true], [true, false], [true, true], [true, true], [true, false], [false, true], [false, true], [true, false], [true, false], [false, false]],
            '05-2023': [[false, false], [false, false], [false, false], [false, true], [true, true], [false, false], [false, false], [false, false], [false, true], [true, true], [false, true], [true, false], [true, false], [true, true], [false, true], [true, false], [false, false], [true, false], [true, false], [true, true], [true, true], [false, false], [true, false], [true, true], [false, false], [false, false], [true, true], [false, false], [false, true], [true, true]],
            '06-2023': [[false, true], [true, false], [false, true], [true, true], [false, false], [false, false], [true, true], [false, true], [false, true], [true, false], [true, true], [false, false], [true, false], [true, false], [true, false], [false, true], [false, false], [false, true], [true, false], [false, true], [false, true], [false, false], [false, true], [false, false], [false, true], [false, false], [false, false], [true, false], [true, false], [true, true], [false, false]],
            '07-2023': [[false, false], [false, false], [true, true], [false, true], [true, false], [false, true], [true, true], [true, false], [false, true], [false, true], [true, true], [true, false], [false, false], [true, false], [false, true], [false, false], [true, true], [false, false], [false, false], [false, true], [false, false], [true, true], [true, true], [false, false], [false, true], [false, true], [false, true], [true, false], [true, false], [false, true], [false, true]],
            '08-2023': [[true, false], [false, true], [false, false], [false, true], [false, true], [false, false], [true, false], [true, true], [true, false], [true, true], [false, false], [false, false], [false, true], [false, false], [true, true], [true, false], [false, true], [false, false], [false, false], [true, false], [false, false], [false, false], [false, true], [false, false], [false, true], [false, false], [false, false], [true, false], [true, false], [false, true]],
            '09-2023': [[false, false], [false, false], [true, false], [true, false], [false, true], [true, true], [false, true], [false, false], [true, true], [false, false], [true, true], [true, false], [true, false], [true, false], [false, false], [true, true], [false, true], [true, false], [false, true], [false, false], [false, true], [true, false], [false, false], [false, true], [true, false], [false, true], [false, false], [true, false], [false, false], [true, false], [true, true]],
            '10-2023': [[false, false], [false, true], [true, true], [true, true], [true, true], [true, false], [false, true], [false, false], [false, false], [false, true], [true, false], [false, true], [false, false], [true, false], [true, false], [false, false], [false, false], [true, false], [false, true], [false, true], [true, true], [true, false], [false, false], [false, false], [true, false], [false, true], [false, false], [true, false], [false, true], [true, true]],
            '11-2023': [[true, false], [false, true], [false, false], [true, true], [false, false], [false, true], [true, false], [false, true], [false, false], [true, true], [true, true], [false, false], [false, false], [false, true], [true, false], [true, true], [false, true], [false, true], [true, false], [true, true], [true, true], [true, false], [false, true], [false, true], [true, true], [true, true], [true, true], [true, false], [false, true], [false, true], [true, true]],
		},
		user2: {
            '00-2023': [[false, false], [false, false], [true, true], [false, false], [true, false], [false, true], [false, true], [false, true], [false, false], [false, false], [false, true], [true, true], [true, true], [false, true], [true, false], [false, true], [false, false], [true, false], [true, false], [true, true], [true, true], [true, true], [false, true], [true, false], [true, false], [false, true], [false, false], [false, false], [true, false], [false, false], [true, true]],
            '01-2023': [[true, true], [true, true], [true, false], [false, false], [false, false], [false, false], [true, true], [false, false], [true, false], [false, true], [true, false], [true, true], [false, true], [false, true], [false, false], [true, true], [false, false], [true, false], [true, true], [true, false], [false, false], [false, true], [false, false], [false, false], [true, false], [false, true], [false, false], [true, true]],
            '02-2023': [[true, false], [true, true], [false, false], [false, false], [false, false], [true, true], [false, false], [true, true], [true, false], [false, true], [true, true], [true, true], [true, true], [false, true], [true, true], [true, true], [true, false], [false, true], [true, false], [true, true], [true, false], [false, false], [true, false], [true, true], [true, false], [false, true], [true, true], [true, false], [true, true], [true, true], [true, false]],
            '03-2023': [[true, false], [false, false], [false, false], [true, true], [true, false], [true, true], [true, false], [true, true], [false, false], [true, true], [false, true], [true, false], [false, false], [true, true], [true, false], [false, false], [true, true], [true, false], [true, false], [false, false], [true, false], [true, true], [true, false], [true, true], [true, false], [true, true], [false, false], [false, true], [true, true], [false, true]],
            '04-2023': [[true, true], [true, true], [true, false], [true, true], [false, false], [true, true], [true, false], [false, false], [true, false], [true, false], [false, false], [true, true], [false, false], [false, true], [true, false], [true, true], [true, true], [true, true], [true, false], [true, true], [true, true], [true, false], [true, true], [true, true], [false, false], [false, false], [false, true], [false, false], [true, false], [true, false], [true, false]],
            '05-2023': [[false, true], [true, true], [false, true], [false, true], [false, true], [false, false], [false, false], [false, false], [false, true], [false, false], [false, true], [false, false], [true, true], [true, true], [true, true], [true, false], [false, true], [true, false], [true, true], [false, false], [true, true], [false, false], [false, true], [true, true], [false, true], [false, false], [false, true], [false, true], [true, true], [true, false]],
            '06-2023': [[true, false], [true, false], [true, false], [false, true], [true, false], [false, true], [true, true], [false, true], [true, false], [false, false], [false, true], [true, false], [false, false], [true, false], [true, true], [false, true], [true, true], [true, false], [false, true], [true, true], [true, false], [true, false], [true, false], [false, false], [true, false], [true, false], [true, true], [false, false], [false, false], [true, false], [false, true]],
            '07-2023': [[false, true], [true, true], [true, false], [false, false], [true, false], [true, true], [false, true], [false, false], [true, false], [false, false], [false, true], [true, false], [true, true], [true, true], [true, false], [true, true], [false, false], [true, false], [false, true], [false, false], [false, true], [true, false], [false, false], [true, false], [true, false], [true, true], [true, true], [false, false], [false, false], [false, false], [false, false]],
            '08-2023': [[true, false], [true, false], [false, false], [false, true], [false, true], [false, false], [true, true], [true, true], [true, true], [false, false], [true, true], [true, false], [false, false], [true, true], [true, false], [true, true], [true, false], [false, false], [false, false], [true, false], [false, true], [false, false], [false, true], [true, true], [false, true], [false, true], [true, true], [false, false], [true, true], [true, true]],
            '09-2023': [[false, false], [false, false], [true, false], [true, true], [true, false], [true, true], [true, false], [false, true], [false, true], [true, false], [true, true], [true, false], [true, false], [true, true], [true, true], [true, false], [true, true], [false, false], [false, false], [true, false], [true, true], [false, true], [false, false], [false, false], [false, true], [true, true], [true, true], [true, true], [false, true], [true, true], [false, false]],
            '10-2023': [[false, false], [true, false], [true, true], [true, true], [true, false], [true, false], [true, true], [true, false], [true, true], [true, true], [false, false], [true, false], [true, false], [true, true], [true, false], [false, true], [true, true], [false, true], [true, false], [true, true], [false, false], [false, true], [true, false], [false, false], [false, true], [true, false], [true, true], [false, true], [true, true], [false, true]],
            '11-2023': [[false, true], [false, true], [false, true], [false, false], [false, true], [true, true], [false, false], [false, true], [false, false], [true, false], [false, true], [true, false], [true, false], [true, false], [false, false], [false, false], [false, false], [true, false], [true, false], [false, true], [false, true], [false, true], [true, false], [true, false], [false, false], [true, true], [true, true], [true, false], [true, false], [true, false], [false, false]],
        },
	},
	reducers: {
		setUserSelections(state, action) {
			const { user, selections } = action.payload;
			state[user] = selections;
		},
	},
});

export const { setUserSelections } = tripSlice.actions;
export default tripSlice.reducer;
